@startuml
abstract class TarjetaSubte{
    -CentralSubte cs

    +TarjetaRecargable(CentralSubte sc)
    +void {abstract} viajar()

    #boolean puedoViajar()
}

class TarjetaFijaSubte{
    -int viajes

    +TarjetaFijaSubte(CentralSubte sc, int viajes)
    +void viajar()
    #boolean puedoViajar()
}

class TarjetaRecargable{
    -double saldo

    +TarjetaRecargable(CentralSubte sc)
    +void viajar()
    #boolean puedoViajar()
}

TarjetaSubte <|-- TarjetaFijaSubte
TarjetaSubte <|-- TarjetaRecargable

class CentralSubte{
    -double costoViaje

    +CentralSubte(double precioInicialViaje)
    +void cambiarPrecio(double precioViaje)
    +double getPrecioViaje()
}

TarjetaSubte *-- CentralSubte

@enduml