@startuml

class TarjetaSubte{

    -double saldo
    -CentralSubte centralEmisora

    +TarjetaSubte(CentralSubte cs)
    +void recargarSaldo(double saldo)
    +double consultarSaldo(double saldo)
    +void viajar()
    -boolean puedoViajar()
}

class CentralSubte{
    -double costoViaje

    +CentralSubte(double precioInicialViaje)
    +void cambiarPrecio(double precioViaje)
    +double getPrecioViaje()
}

TarjetaSubte *-- CentralSubte

@enduml